version: '3.8'

services:
  my-app-dockerfile:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - CUSTOM_NAME=my-app-dockerfile
      - CUSTOM_PORT=8080
    ports:
      - "5051:8080"

  my-app-image:
    image: my-app
    environment:
      - CUSTOM_NAME=my-app-image
      - CUSTOM_PORT=8080
    ports:
      - "5052:8080"
